### ISSUE TITLE
Works in debug mode but does not work in release mode.

### ISSUE THREAD

**Issue by musabibnusiraj** [bawantha/payhere_flutter#2]
@bawantha 
I ran `flutter build apk`

_build\app\outputs\flutter-apk\app-release.apk_

I installed this build APK file. on my mobile.
![a](https://user-images.githubusercontent.com/47845204/92521677-41411d00-f23b-11ea-873d-29ebeec8b86f.png)

The above screen opens then I choose one from the listed methods.
after that screen closed.

but works fine while debugging.
 The below screen shows on debug mode.

![b](https://user-images.githubusercontent.com/47845204/92521753-63d33600-f23b-11ea-8a06-a1700317fdf8.png)

is this error occur because of the sandbox?
or the error occurs from any other reasons?

**Comment by musabibnusiraj** [comment]
> I ran `flutter build apk`
> 
> _build\app\outputs\flutter-apk\app-release.apk_
> 
> I installed this build APK file. on my mobile.
> ![a](https://user-images.githubusercontent.com/47845204/92521677-41411d00-f23b-11ea-873d-29ebeec8b86f.png)
> 
> The above screen opens then I choose one from the listed methods.
> after that screen closed.
> 
> but works fine while debugging.
> The below screen shows on debug mode.
> 
> ![b](https://user-images.githubusercontent.com/47845204/92521753-63d33600-f23b-11ea-8a06-a1700317fdf8.png)
> 
> is this error occur because of the sandbox?
> or the error occurs from any other reasons?

**Comment by bawantha** [comment]
can you post reposnse from Payhere

**Comment by musabibnusiraj** [comment]
### The built apk

_build\app\outputs\flutter-apk\app-release.apk_

I installed the above apk.

### responseText 

`{message: null, status: null}`


But on debug mode, The Payhere works fine.

**Comment by bawantha** [comment]
I assume this is problem with code shrink can you build app with `flutter build apk --no-shrink`

**Comment by musabibnusiraj** [comment]
Thank you.
It's working fine.
